name: fr_fuse_env
channels:
  - pyg
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.38
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - curl=7.88.1
  - cycler=0.11.0
  - cython=0.29.32
  - cytoolz=0.12.0
  - dask-core=2023.4.0
  - dbus=1.13.18
  - expat=2.4.9
  - ffmpeg=4.3
  - filelock=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.4.0
  - gcc=12.1.0
  - gcc_impl_linux-64=12.1.0
  - gdal=3.6.2
  - geos=3.8.0
  - geotiff=1.7.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.28.0
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - json-c=0.16
  - jxrlib=1.1
  - kealib=1.5.0
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=12.2.0
  - libgdal=3.6.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=12.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.9
  - libsanitizer=12.1.0
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.8.0
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - munkres=1.1.4
  - namedlist=1.8
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - nspr=4.33
  - nss=3.74
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1u
  - packaging=23.1
  - partd=1.4.0
  - pcre=8.45
  - pcre2=10.37
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.11
  - postgresql=12.9
  - proj=6.2.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qhull=2020.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.29.0
  - scikit-image=0.19.2
  - scipy=1.8.1
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - sympy=1.11.1
  - sysroot_linux-64=2.12
  - tifffile=2021.4.8
  - tiledb=2.3.3
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tornado=6.1
  - tqdm=4.65.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.38.4
  - xerces-c=3.2.4
  - xz=5.2.10
  - yaml=0.2.5
  - zfp=0.5.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - bm3d==4.0.1
      - bm4d==4.2.3
      - mpmath==1.2.1
      - pymanopt==2.1.1
      - pyqt5-sip==12.11.0
      - pytorch-minimize==0.0.2
      - recordclass==0.18.4
